### ISSUE TITLE
move from  material-ui to react-bootstrap

### ISSUE THREAD

**Issue by rohit-ravikoti** [WilliamTaorminaOrganization/open_castings_components#14]
Everything does NOT have to be styled exactly the way it is in material-ui. Just use equivalent components from react-bootstrap.

I just made a commit which removed all components that were using material-ui. You can take a look at #15 to copy over the following components and covert them to bootstrap:

- [x] Audition
 - [x] AuditionOverview
 - [x] AuditionWelcome
- [x] Profile
 - [x] ProfileBasicStats
 - [x] ProfileEducationTraining
 - [x] ProfileEducationTrainingItem
 - [x] ProfileExperienceCategory
 - [x] ProfileExperienceItem
 - [x] ProfileJobs (remove editable portion)
 - [x] ProfileOverview
 - [x] ProfileSkills
 - [x] ProfileTitle (remove editable portion)

**Comment by rohit-ravikoti** [comment]
@monaldev please make sure not to copy over the editable parts of ProfileTitle and ProfileJobs. Just keep the normal view.

**Comment by monaldev** [comment]
@rohit-ravikoti  I have sent pull request please review that
